#!/usr/bin/env python3
"""Generate LaTeX tables for the report from repository artifacts."""

from __future__ import annotations

import csv
import json
import math
import re
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SECTIONS_DIR = ROOT / "reports" / "tables"
DATASET_COUNTS = ROOT / "reports" / "dataset_counts.json"
EVAL_REPORT = ROOT / "reports" / "evaluation_report.json"
TRAIN_HISTORY = ROOT / "models" / "logs" / "train_history.csv"
APP_FILE = ROOT / "app.py"


def _require(path: Path) -> Path:
    if not path.exists():
        raise SystemExit(f"Required artifact not found: {path}")
    return path


def _latex_escape(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "<": r"\textless{}",
        ">": r"\textgreater{}",
    }
    text = str(value)
    for src, dst in replacements.items():
        text = text.replace(src, dst)
    return text


def _pretty_label(label: str) -> str:
    if "___" in label:
        crop, disease = label.split("___", 1)
        crop = crop.replace("_", " ").replace(",", "")
        disease = disease.replace("_", " ")
        return f"{crop} / {disease}"
    return label.replace("_", " ")


def _write(path: Path, content: str) -> None:
    path.write_text(content.rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {path.relative_to(ROOT)}")


def _load_dataset_counts() -> dict:
    return json.loads(_require(DATASET_COUNTS).read_text(encoding="utf-8"))


def _load_eval_report() -> dict:
    return json.loads(_require(EVAL_REPORT).read_text(encoding="utf-8"))


def _load_train_history() -> list[dict]:
    rows: list[dict] = []
    with _require(TRAIN_HISTORY).open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            rows.append(
                {
                    "epoch": int(row["epoch"]),
                    "accuracy": float(row["accuracy"]),
                    "loss": float(row["loss"]),
                    "val_accuracy": float(row["val_accuracy"]),
                    "val_loss": float(row["val_loss"]),
                }
            )
    if not rows:
        raise SystemExit(f"No rows found in training history: {TRAIN_HISTORY}")
    return rows


def _load_class_order() -> list[str]:
    class_indices_path = ROOT / "models" / "class_indices.json"
    class_indices = json.loads(_require(class_indices_path).read_text(encoding="utf-8"))
    return [label for label, _ in sorted(class_indices.items(), key=lambda item: item[1])]


def _crop_of(label: str) -> str:
    if "___" in label:
        return label.split("___", 1)[0].replace(",", "").replace("_", " ")
    return label.replace("_", " ")


def _split_table_rows(rows: list[str], parts: int) -> list[list[str]]:
    chunk_size = math.ceil(len(rows) / parts)
    return [rows[i:i + chunk_size] for i in range(0, len(rows), chunk_size)]


def _parse_routes() -> list[tuple[str, str, str]]:
    text = _require(APP_FILE).read_text(encoding="utf-8")
    route_pattern = re.compile(
        r"@app\.route\('([^']+)'\s*(?:,\s*methods=\[([^\]]+)\])?\)\s*\ndef\s+([A-Za-z_][A-Za-z0-9_]*)",
        re.MULTILINE,
    )
    routes = []
    for path, methods, func_name in route_pattern.findall(text):
        clean_methods = "GET"
        if methods:
            clean_methods = "/".join(part.strip().strip("'") for part in methods.split(","))
        routes.append((path, clean_methods, func_name))
    return routes


def build_dataset_summary() -> str:
    counts = _load_dataset_counts()
    classes = len(counts["train"]["per_class"])
    total = (
        counts["train"]["total_images"]
        + counts["val"]["total_images"]
        + counts["test"]["total_images"]
    )
    return rf"""
% Auto-generated by tools/reporting/generate_report_tables.py
\begin{{table}}[!t]
\caption{{Repository dataset summary.}}
\label{{tab:dataset_summary}}
\centering
\small
\begin{{tabular}}{{lrr}}
\toprule
Split & Images & Classes \\
\midrule
Train & {counts['train']['total_images']:,} & {classes} \\
Validation & {counts['val']['total_images']:,} & {classes} \\
Test & {counts['test']['total_images']:,} & {classes} \\
\midrule
Total & {total:,} & {classes} \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""


def build_crop_summary() -> str:
    counts = _load_dataset_counts()
    report = _load_eval_report()
    per_crop_counts: dict[str, dict[str, int]] = defaultdict(lambda: {"train": 0, "val": 0, "test": 0, "classes": 0})
    crop_metrics: dict[str, list[float]] = defaultdict(list)
    crop_support: dict[str, int] = defaultdict(int)

    for split in ("train", "val", "test"):
        seen: set[str] = set()
        for label, count in counts[split]["per_class"].items():
            crop = _crop_of(label)
            per_crop_counts[crop][split] += int(count)
            if split == "train" and crop not in seen:
                seen.add(crop)
        if split == "train":
            for label in counts["train"]["per_class"]:
                crop = _crop_of(label)
                per_crop_counts[crop]["classes"] += 1

    for label, data in report["per_class_metrics"].items():
        crop = _crop_of(label)
        crop_metrics[crop].append(float(data["f1"]))
        crop_support[crop] += int(data["support"])

    rows = []
    for crop in sorted(per_crop_counts, key=lambda key: per_crop_counts[key]["train"], reverse=True):
        train_count = per_crop_counts[crop]["train"]
        val_count = per_crop_counts[crop]["val"]
        test_count = per_crop_counts[crop]["test"]
        total = train_count + val_count + test_count
        macro_f1 = 100 * sum(crop_metrics[crop]) / max(len(crop_metrics[crop]), 1)
        rows.append(
            f"{_latex_escape(crop)} & "
            f"{per_crop_counts[crop]['classes']} & "
            f"{train_count:,} & "
            f"{val_count:,} & "
            f"{test_count:,} & "
            f"{total:,} & "
            f"{macro_f1:.2f} \\\\"
        )

    body = "\n".join(rows)
    return rf"""
% Auto-generated by tools/reporting/generate_report_tables.py
\begin{{table*}}[!t]
\caption{{Crop-level dataset composition and validation macro F1.}}
\label{{tab:crop_summary}}
\centering
\small
\begin{{tabular}}{{lrrrrrr}}
\toprule
Crop & Classes & Train & Validation & Test & Total & Macro F1 (\%) \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{table*}}
"""


def build_training_config() -> str:
    rows = [
        ("Backbone", "EfficientNetV2-S"),
        ("Input size", "224 x 224"),
        ("Classes", "46"),
        ("Batch size", "64"),
        ("Phase 1 epochs", "5"),
        ("Phase 2 epochs", "10"),
        ("Phase 1 LR", "2e-3"),
        ("Phase 2 LR", "1e-4"),
        ("Optimizer", "AdamW"),
        ("Label smoothing", "0.1"),
        ("MixUp", "Enabled (alpha=0.3)"),
        ("CutMix", "Enabled (alpha=1.0)"),
        ("Checkpoint monitor", "Validation accuracy"),
        ("Mixed precision", "Enabled when GPU is available"),
    ]
    body = "\n".join(f"{_latex_escape(k)} & {_latex_escape(v)} \\\\" for k, v in rows)
    return rf"""
% Auto-generated by tools/reporting/generate_report_tables.py
\begin{{table}}[!htbp]
\caption{{Training configuration used by the shipped checkpoint.}}
\label{{tab:training_config}}
\centering
\small
\begin{{tabularx}}{{\columnwidth}}{{L L}}
\toprule
Setting & Value \\
\midrule
{body}
\bottomrule
\end{{tabularx}}
\end{{table}}
"""


def build_system_inventory() -> str:
    rows = [
        ("train_model.py", "Primary two-stage training pipeline", "Checkpoint, logs, class indices"),
        ("evaluate_model.py", "Held-out validation evaluation", "JSON and Markdown reports"),
        ("scripts/generate_figures.py", "Figure generation", "Confusion matrix, learning curves, prediction panels"),
        ("predict.py", "CLI and Python inference entrypoint", "Predicted label and confidence"),
        ("app.py", "Flask web UI and workflow control", "Upload, prediction, health, and control endpoints"),
        ("tools/reporting/generate_report_tables.py", "Report table generator", "Compiled PDF via latexmk"),
    ]
    body = "\n".join(
        f"{_latex_escape(module)} & {_latex_escape(role)} & {_latex_escape(output)} \\\\"
        for module, role, output in rows
    )
    return rf"""
% Auto-generated by tools/reporting/generate_report_tables.py
\begin{{table*}}[!t]
\caption{{Repository modules referenced directly in the report workflow.}}
\label{{tab:system_inventory}}
\centering
\small
\begin{{tabularx}}{{\textwidth}}{{L L L}}
\toprule
Module & Role & Primary output \\
\midrule
{body}
\bottomrule
\end{{tabularx}}
\end{{table*}}
"""


def build_metrics_table() -> str:
    report = _load_eval_report()
    history = _load_train_history()
    best = max(history, key=lambda row: row["val_accuracy"])
    epochs = len(history)
    metrics = report["metrics"]
    return rf"""
% Auto-generated by tools/reporting/generate_report_tables.py
\begin{{table}}[!htbp]
\caption{{Held-out validation performance for the shipped checkpoint.}}
\label{{tab:overall_metrics}}
\centering
\small
\begin{{tabular}}{{lr}}
\toprule
Metric & Value \\
\midrule
Validation samples & {report['validation_samples']:,} \\
Accuracy & {metrics['accuracy'] * 100:.2f}\% \\
Macro precision & {metrics['macro_precision'] * 100:.2f}\% \\
Macro recall & {metrics['macro_recall'] * 100:.2f}\% \\
Macro F1 & {metrics['macro_f1'] * 100:.2f}\% \\
Loss & {metrics['loss']:.4f} \\
Best epoch & {best['epoch'] + 1} / {epochs} \\
Best val.\ loss & {best['val_loss']:.4f} \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""


def build_per_class_table() -> str:
    report = _load_eval_report()
    rows = sorted(
        report["per_class_metrics"].items(),
        key=lambda item: (item[1]["f1"], item[1]["recall"], item[0]),
    )[:5]
    body = "\n".join(
        f"{_latex_escape(_pretty_label(label))} & "
        f"{metrics['precision'] * 100:.2f} & "
        f"{metrics['recall'] * 100:.2f} & "
        f"{metrics['f1'] * 100:.2f} & "
        f"{metrics['support']} \\\\"
        for label, metrics in rows
    )
    return rf"""
% Auto-generated by tools/reporting/generate_report_tables.py
\begin{{table}}[!htbp]
\caption{{Lowest-F1 validation classes.}}
\label{{tab:hard_classes}}
\centering
\small
\begin{{tabularx}}{{\columnwidth}}{{Lrrrr}}
\toprule
Class & Prec. & Recall & F1 & Support \\
\midrule
{body}
\bottomrule
\end{{tabularx}}
\end{{table}}
"""


def build_confusion_table() -> str:
    report = _load_eval_report()
    rows = report["top_confused_pairs"][:5]
    body = "\n".join(
        f"{_latex_escape(_pretty_label(row['true_class']))} & "
        f"{_latex_escape(_pretty_label(row['pred_class']))} & "
        f"{int(row['count'])} \\\\"
        for row in rows
    )
    return rf"""
% Auto-generated by tools/reporting/generate_report_tables.py
\begin{{table}}[!htbp]
\caption{{Most frequent off-diagonal validation confusions.}}
\label{{tab:top_confusions}}
\centering
\small
\begin{{tabularx}}{{\columnwidth}}{{L L r}}
\toprule
True class & Predicted as & Count \\
\midrule
{body}
\bottomrule
\end{{tabularx}}
\end{{table}}
"""


def build_crop_metrics_table() -> str:
    report = _load_eval_report()
    per_crop: dict[str, list[float]] = defaultdict(list)
    support_by_crop: dict[str, int] = defaultdict(int)
    for label, data in report["per_class_metrics"].items():
        crop = _crop_of(label)
        per_crop[crop].append(float(data["f1"]))
        support_by_crop[crop] += int(data["support"])

    rows = []
    for crop in sorted(per_crop, key=lambda key: sum(per_crop[key]) / len(per_crop[key])):
        macro_f1 = 100.0 * sum(per_crop[crop]) / len(per_crop[crop])
        rows.append(f"{_latex_escape(crop)} & {len(per_crop[crop])} & {support_by_crop[crop]} & {macro_f1:.2f} \\\\")
    body = "\n".join(rows)
    return rf"""
% Auto-generated by tools/reporting/generate_report_tables.py
\begin{{table}}[!htbp]
\caption{{Validation macro F1 aggregated by crop family.}}
\label{{tab:crop_metrics}}
\centering
\small
\begin{{tabular}}{{lrrr}}
\toprule
Crop & Classes & Support & Macro F1 (\%) \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{table}}
"""


def build_endpoint_inventory_table() -> str:
    descriptions = {
        "/": "Main web interface",
        "/predict": "Image upload and prediction",
        "/health": "Health probe and model status",
        "/control/actions": "Available workflow actions",
        "/control/run/<action_key>": "Start training, fine-tuning, evaluation, or figure generation",
        "/control/jobs": "List workflow job history",
        "/control/system": "Expose runtime compute info",
        "/control/stop/<job_id>": "Terminate running workflow job",
    }
    rows = []
    for path, methods, _ in _parse_routes():
        rows.append(f"{_latex_escape(path)} & {_latex_escape(methods)} & {_latex_escape(descriptions.get(path, 'Application route'))} \\\\")
    body = "\n".join(rows)
    return rf"""
% Auto-generated by tools/reporting/generate_report_tables.py
\begin{{table*}}[!b]
\caption{{HTTP routes exposed by the Flask application.}}
\label{{tab:endpoints}}
\centering
\footnotesize
\begin{{tabularx}}{{\textwidth}}{{L l L}}
\toprule
Route & Method & Purpose \\
\midrule
{body}
\bottomrule
\end{{tabularx}}
\end{{table*}}
"""


def build_full_dataset_inventory_longtable() -> str:
    counts = _load_dataset_counts()
    rows = []
    for label, train_count in sorted(counts["train"]["per_class"].items()):
        val_count = counts["val"]["per_class"].get(label, 0)
        test_count = counts["test"]["per_class"].get(label, 0)
        total = int(train_count) + int(val_count) + int(test_count)
        rows.append(
            f"{_latex_escape(_pretty_label(label))} & {int(train_count):,} & {int(val_count):,} & {int(test_count):,} & {total:,} \\\\"
        )

    body = "\n".join(rows)
    return rf"""
% Auto-generated by tools/reporting/generate_report_tables.py
\begingroup
\scriptsize
\setlength{{\tabcolsep}}{{8pt}}
\begin{{longtable}}{{@{{}}p{{0.48\textwidth}}rrrr@{{}}}}
\caption{{Full class inventory with split counts.}}
\label{{tab:dataset_inventory}}\\
\toprule
Class & Train & Validation & Test & Total \\
\midrule
\endfirsthead
\caption[]{{Full class inventory with split counts (continued).}}\\
\toprule
Class & Train & Validation & Test & Total \\
\midrule
\endhead
\midrule
\multicolumn{{5}}{{r}}{{Continued on next page}}\\
\endfoot
\bottomrule
\endlastfoot
{body}
\end{{longtable}}
\endgroup
"""


def build_full_per_class_metric_longtable() -> str:
    report = _load_eval_report()
    rows = []
    for label, data in sorted(report["per_class_metrics"].items()):
        rows.append(
            f"{_latex_escape(_pretty_label(label))} & "
            f"{data['precision'] * 100:.2f} & "
            f"{data['recall'] * 100:.2f} & "
            f"{data['f1'] * 100:.2f} & "
            f"{int(data['support'])} \\\\"
        )

    body = "\n".join(rows)
    return rf"""
% Auto-generated by tools/reporting/generate_report_tables.py
\begingroup
\scriptsize
\setlength{{\tabcolsep}}{{8pt}}
\begin{{longtable}}{{@{{}}p{{0.46\textwidth}}rrrr@{{}}}}
\caption{{Full per-class validation metrics.}}
\label{{tab:full_metrics}}\\
\toprule
Class & Precision (\%) & Recall (\%) & F1 (\%) & Support \\
\midrule
\endfirsthead
\caption[]{{Full per-class validation metrics (continued).}}\\
\toprule
Class & Precision (\%) & Recall (\%) & F1 (\%) & Support \\
\midrule
\endhead
\midrule
\multicolumn{{5}}{{r}}{{Continued on next page}}\\
\endfoot
\bottomrule
\endlastfoot
{body}
\end{{longtable}}
\endgroup
"""


def main() -> None:
    SECTIONS_DIR.mkdir(parents=True, exist_ok=True)
    _write(SECTIONS_DIR / "generated_dataset_summary.tex", build_dataset_summary())
    _write(SECTIONS_DIR / "generated_crop_summary.tex", build_crop_summary())
    _write(SECTIONS_DIR / "generated_training_config.tex", build_training_config())
    _write(SECTIONS_DIR / "generated_system_inventory.tex", build_system_inventory())
    _write(SECTIONS_DIR / "generated_metrics.tex", build_metrics_table())
    _write(SECTIONS_DIR / "generated_crop_metrics.tex", build_crop_metrics_table())
    _write(SECTIONS_DIR / "generated_per_class.tex", build_per_class_table())
    _write(SECTIONS_DIR / "generated_confusions.tex", build_confusion_table())
    _write(SECTIONS_DIR / "generated_endpoint_inventory.tex", build_endpoint_inventory_table())
    _write(SECTIONS_DIR / "generated_full_dataset_inventory_longtable.tex", build_full_dataset_inventory_longtable())
    _write(SECTIONS_DIR / "generated_full_per_class_metrics_longtable.tex", build_full_per_class_metric_longtable())


if __name__ == "__main__":
    main()
